prompt_tariffs = """
You are assisting me in analyzing financial analyst reports. Each report is about a single company. The analyst report will be supplied as the user prompt.

## CRITICAL FOCUS DIRECTIVE ##
You must strictly isolate your analysis to TARIFFS ONLY. Given the potential length of the transcript, do not lose focus or hallucinate data. If the firm's actions are driven by other macroeconomic factors or different policies (like sanctions or export controls), DO NOT attribute them to tariffs. If tariffs are not discussed, strictly return 0 and "NaN" for all corresponding fields.

## Response Instructions: Part 1 (Analysis) ##
The first part of your response should be an analysis of whether the analyst is reporting that the firm's decisions are being affected by tariff policies. Tariffs are defined as taxes imposed on imported foreign goods. These must be imposed by the importing country in order to be classified as tariffs. Tariffs are not export restrictions, quotas, embargoes, financial sanctions, boycotts, or non-tariff barriers.

This part of your response should be enclosed between the tags <ANALYSIS> and </ANALYSIS>. Keep your analysis to 300 words or less. Make sure to cover all of the following points in your summary analysis:
- Whether tariffs are discussed explicitly or implicitly (e.g., by not using the word "tariffs" but referencing impacts on the firm's business that clearly relate to tariffs).
- Whether the report discusses current tariffs (i.e., tariffs that have already been imposed) or the potential of future tariffs (i.e., tariffs that have not yet been imposed).
- Whether the report discusses tariffs on the goods that the firm sells, or on those that the firm buys.
- The nature and details of the tariff policies that are discussed.
- The countries that are imposing the tariffs and those that are subject to the tariffs.
- Any impacts on the firm's current profits.
- Any potential impact on the firm's future profits.
- Any impacts on the firm's behavior (e.g., in terms of investment, pricing, employment, inventory, R&D, project delay, supply chains, or other future plans).
- Any details on the geographies affected by the changes in the firm's behavior (e.g., if the firm reports importing less, report from which destination).

## Response Instructions: Part 2 (Structured JSON Output) ##
The second part of your response should be a structured output in JSON format that recaps your analysis in a structured way. This part of your response should be enclosed between the tags <JSON> and </JSON>. The JSON output must have the following fields exactly. Please make sure to enforce the JSON schema specified below strictly: i.e., the column names should correspond exactly to those listed below:
1. A boolean flag called "effect_any", which should be 1 if the report discusses tariffs at any point, and 0 otherwise. Even if the term "tariffs" is not explicitly used throughout the report, you should return a 1 if the report discusses impacts on the firm's business that clearly relate to tariffs.
2. A boolean flag called "effect_current", which should be 1 if the report explicitly or implicitly discusses tariffs that are currently in effect and that impact the firm's business, and 0 otherwise. Please do not classify tariffs that might imposed in the future as a 1 in this flag.
3. A boolean flag called "effect_future", which should be 1 if the report explicitly or implicitly discusses tariffs that might be imposed in the future but are not currently in effect and that might impact the firm's business, and 0 otherwise. Please do not classify tariffs that are currently in effect as a 1 in this flag.
4. A field called "countries_imposing", listing the countries whose tariffs policy the report discusses, if any. For example, if the report discusses concerns about tariffs imposed by the US government on goods imported from China, this field should say "USA".
5. A field called "countries_receiving", listing the entities (countries) targeted by the tariffs discussed by the report, if any. For example, if the report discusses concerns about tariffs imposed by the US government on goods imported from China, this field should say "China".
6. A field called "product_receiving", listing the goods that the firm sells that are targeted by the tariffs, if any. For example, if the report discusses current or future tariffs imposed by the US government on steel that the firm sells to its US customers, this field should say "steel".
7. A field called "input_receiving", listing the goods that the firm buys that are targeted by tariffs, if any. For example, if the report discusses current or future tariffs imposed by the US government on steel that the firm buys from Mexico, this field should say "steel".
8. A boolean flag called "investment_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its investment as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's investment decisions to tariffs.
9. A boolean flag called "investment_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its investment as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's investment decisions to tariffs.
10. A field called "countries_investment_up", listing the countries where the report discusses that the firm is increasing or planning to increase investment as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
11. A field called "countries_investment_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease investment as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
12. A boolean flag called "domestic_investment_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its investment in its headquarter country as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's investment decisions to tariffs.
13. A boolean flag called "domestic_investment_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its investment in its headquarter country as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's investment decisions to tariffs.
14. A boolean flag called "labor_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's employment decisions to tariffs.
15. A boolean flag called "labor_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's employment decisions to tariffs.
16. A field called "countries_labor_up", listing the countries where the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
17. A field called "countries_labor_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
18. A boolean flag called "domestic_labor_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked in its headquarter country as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's employment decisions to tariffs.
19. A boolean flag called "domestic_labor_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked in its headquarter country as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's employment decisions to tariffs.
20. A boolean flag called "sales_price_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the price it charges for the products it sells as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's product pricing decisions to tariffs.
21. A boolean flag called "sales_price_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease the price it charges for the products it sells as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's product pricing decisions to tariffs.
22. A field called "countries_sales_price_up", listing the countries where the report discusses that the firm is increasing or planning to increase the price it charges for the products it sells as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
23. A field called "countries_sales_price_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the price it charges for the products it sells as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
24. A boolean flag called "input_price_up", which should be 1 if the firm says it faces or expects to face higher prices on the inputs it purchases as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's input prices to tariffs.
25. A boolean flag called "input_price_down", which should be 1 if the firm says it faces or expects to face lower prices on the inputs it purchases as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's input prices to tariffs.
26. A field called "countries_input_price_up", listing the countries where the report discusses that the firm is facing or expecting to face higher prices on the inputs it purchases as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
27. A field called "countries_input_price_down", listing the countries where the report discusses that the firm is facing or expecting to face lower prices on the inputs it purchases as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
28. A boolean flag called "sales_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the quantities of the products that it sells as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's product sales to tariffs.
29. A boolean flag called "sales_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease the quantities of the products that it sells as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's product sales to tariffs.
30. A field called "countries_sales_up", listing the countries where the report discusses that the firm is increasing or planning to increase the quantities of the products that it sells as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
31. A field called "countries_sales_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the quantities of the products that it sells as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
32. A boolean flag called "input_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the quantities of the inputs that it is purchasing as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's input quantities to tariffs.
33. A boolean flag called "input_down", which should be 1 if the firm says it is decreasing or planning to decrease the quantities of the inputs that it is purchasing as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's input quantities to tariffs.
34. A field called "countries_input_up", listing the countries where the report discusses that the firm is increasing or planning to increase the quantities of the inputs that it is purchasing as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
35. A field called "countries_input_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the quantities of the products as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
36. A boolean flag called "inventory_product_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of inventory of the products it sells as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in he firm's inventory decisions to tariffs.
37. A boolean flag called "inventory_product_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of inventory of the products it sells as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's inventory decisions to tariffs.
38. A boolean flag called "inventory_input_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of inventory of inputs it purchases as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's inventory decisions to tariffs.
39. A boolean flag called "inventory_input_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of inventory of inputs it purchases as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's inventory decisions to tariffs.
40. A boolean flag called "rd_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of research and development it undertakes as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's research and development decisions to tariffs.
41. A boolean flag called "rd_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of research and development it undertakes as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's research and development decisions to tariffs.
42. A boolean flag called "delay", which should be 1 if the report discusses that the firm is delaying a decision as a result of current or future tariffs. Only set the flag to 1 if the report explicitly attributes the delay to tariffs.
43. A boolean flag called "supply_chain_adj", which should be 1 if the report discusses that the firm is adjusting its supply chain as a result of current or future tariffs. Only set the flag to 1 if the report explicitly attributes adjusting the firm's supply chains due to tariffs.
44. A field called "countries_supply_chain_adj_towards", listing the countries where the report discusses that the firm is increasing the exposure of its supply chain as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
45. A field called "countries_supply_chain_adj_away", listing the countries where the report discusses that the firm is reducing the exposure of its supply chain as a result of current or future tariffs. If no country is specified or it is unclear, report "NaN".
46. A boolean flag called "lobbying_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase its lobbying activity as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's lobbying policy to tariffs.
47. A boolean flag called "lobbying_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease its lobbying activity as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's lobbying policy to tariffs.
48. A boolean flag called "profit_margin_up", which should be 1 if the report discusses that the firm's profit margins have increased or are expected to increase as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's profit margins to tariffs.
49. A boolean flag called "profit_margin_down", which should be 1 if the report discusses that the firm's profit margins have decreased or are expected to decreased as a result of current or future tariffs and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's profit margins to tariffs.
50. A boolean flag called "financing_adj", which should be 1 if the report discusses that the firm is adjusting its financing decisions in response to current or future tariffs. Only set the flag to 1 if the report explicitly attributes the adjustment of the firm's financing decisions to tariffs.
51. A boolean flag called "negative_impact", which should be 1 if the report discusses any negative impact on the firm's business as a result of current or future tariffs and 0 otherwise.
52. A boolean flag called "positive_impact", which should be 1 if the report discusses any positive impact on the firm's business as a result of current or future tariffs and 0 otherwise.

## Response Instructions: Part 3 (Summary) ##
Write a single summary of 100 words or fewer that captures only how the firm is (or may be) affected by tariffs. Omit all unrelated content. If the firm is not affected by any tariffs, write "Not affected." Enclose this analysis between the tags <SUMMARY> and </SUMMARY>.

## Response Instructions: Part 4 (Evaluation) ##
The fourth part of your response should be an evaluation of how well the JSON structured summary agrees with your initial analysis. Keep the evaluation to 100 words or less. This part of your response should be enclosed between the tags <EVAL> and </EVAL> and be 100 words or less.

## Important Notes ##
- Do not consider restrictions on exports (imposed by the seller country) or generic sanctions as indications of tariffs. Tariffs must be taxes imposed by the importing country.
"""

prompt_sanctions = """
You are assisting me in analyzing financial analyst reports. Each report is about a single company. The analyst report will be supplied as the user prompt.

## CRITICAL FOCUS DIRECTIVE ##
You must strictly isolate your analysis to SANCTIONS ONLY. Given the potential length of the transcript, do not lose focus or hallucinate data. If the firm's actions are driven by other macroeconomic factors or different policies (like tariffs or export controls), DO NOT attribute them to sanctions. If sanctions are not discussed, strictly return 0 and "NaN" for all corresponding fields.

## Response Instructions: Part 1 (Analysis) ##
The first part of your response should be an analysis of whether the analyst is reporting that the firm's decisions are being affected by sanction policies. Sanctions are defined as government-imposed restrictions on trade or financial transactions designed to coerce, punish, or deter targeted firms or governments. Sanctions are not import tariffs, standard export controls, or voluntary boycotts.

This part of your response should be enclosed between the tags <ANALYSIS> and </ANALYSIS>. Keep your analysis to 300 words or less. Make sure to cover all of the following points in your summary analysis:
- Whether sanctions are discussed explicitly or implicitly (e.g., by not using the word "sanctions" but referencing impacts on the firm's business that clearly relate to sanctions).
- Whether the report discusses current sanctions (i.e., sanctions that have already been imposed) or the potential of future sanctions (i.e., sanctions that have not yet been imposed).
- Whether the report discusses sanctions on the goods or services that the firm sells, or on those that the firm buys.
- The nature and details of the sanction policies that are discussed.
- The countries that are imposing the sanctions and those that are subject to the sanctions.
- Any impacts on the firm's current profits.
- Any potential impact on the firm's future profits.
- Any impacts on the firm's behavior (e.g., in terms of investment, pricing, employment, inventory, R&D, project delay, supply chains, or other future plans).
- Any details on the geographies affected by the changes in the firm's behavior.

## Response Instructions: Part 2 (Structured JSON Output) ##
The second part of your response should be a structured output in JSON format that recaps your analysis in a structured way. This part of your response should be enclosed between the tags <JSON> and </JSON>. The JSON output must have the following fields exactly. Please make sure to enforce the JSON schema specified below strictly: i.e., the column names should correspond exactly to those listed below:
1. A boolean flag called "effect_any", which should be 1 if the report discusses sanctions at any point, and 0 otherwise. Even if the term "sanctions" is not explicitly used throughout the report, you should return a 1 if the report discusses impacts on the firm's business that clearly relate to sanctions.
2. A boolean flag called "effect_current", which should be 1 if the report explicitly or implicitly discusses sanctions that are currently in effect and that impact the firm's business, and 0 otherwise. Please do not classify sanctions that might imposed in the future as a 1 in this flag.
3. A boolean flag called "effect_future", which should be 1 if the report explicitly or implicitly discusses sanctions that might be imposed in the future but are not currently in effect and that might impact the firm's business, and 0 otherwise. Please do not classify sanctions that are currently in effect as a 1 in this flag.
4. A field called "countries_imposing", listing the countries whose sanctions policy the report discusses, if any.
5. A field called "countries_receiving", listing the entities (countries) targeted by the sanctions discussed by the report, if any.
6. A field called "product_receiving", listing the goods that the firm sells that are targeted by the sanctions, if any.
7. A field called "input_receiving", listing the goods that the firm buys that are targeted by sanctions, if any.
8. A boolean flag called "investment_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its investment as a result of current or future sanctions and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's investment decisions to sanctions.
9. A boolean flag called "investment_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its investment as a result of current or future sanctions and 0 otherwise.
10. A field called "countries_investment_up", listing the countries where the report discusses that the firm is increasing or planning to increase investment as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
11. A field called "countries_investment_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease investment as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
12. A boolean flag called "domestic_investment_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its investment in its headquarter country as a result of current or future sanctions and 0 otherwise.
13. A boolean flag called "domestic_investment_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its investment in its headquarter country as a result of current or future sanctions and 0 otherwise.
14. A boolean flag called "labor_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked as a result of current or future sanctions and 0 otherwise.
15. A boolean flag called "labor_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked as a result of current or future sanctions and 0 otherwise.
16. A field called "countries_labor_up", listing the countries where the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
17. A field called "countries_labor_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
18. A boolean flag called "domestic_labor_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked in its headquarter country as a result of current or future sanctions and 0 otherwise.
19. A boolean flag called "domestic_labor_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked in its headquarter country as a result of current or future sanctions and 0 otherwise.
20. A boolean flag called "sales_price_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the price it charges for the products it sells as a result of current or future sanctions and 0 otherwise.
21. A boolean flag called "sales_price_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease the price it charges for the products it sells as a result of current or future sanctions and 0 otherwise.
22. A field called "countries_sales_price_up", listing the countries where the report discusses that the firm is increasing or planning to increase the price it charges for the products it sells as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
23. A field called "countries_sales_price_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the price it charges for the products it sells as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
24. A boolean flag called "input_price_up", which should be 1 if the firm says it faces or expects to face higher prices on the inputs it purchases as a result of current or future sanctions and 0 otherwise.
25. A boolean flag called "input_price_down", which should be 1 if the firm says it faces or expects to face lower prices on the inputs it purchases as a result of current or future sanctions and 0 otherwise.
26. A field called "countries_input_price_up", listing the countries where the report discusses that the firm is facing or expecting to face higher prices on the inputs it purchases as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
27. A field called "countries_input_price_down", listing the countries where the report discusses that the firm is facing or expecting to face lower prices on the inputs it purchases as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
28. A boolean flag called "sales_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the quantities of the products that it sells as a result of current or future sanctions and 0 otherwise.
29. A boolean flag called "sales_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease the quantities of the products that it sells as a result of current or future sanctions and 0 otherwise.
30. A field called "countries_sales_up", listing the countries where the report discusses that the firm is increasing or planning to increase the quantities of the products that it sells as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
31. A field called "countries_sales_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the quantities of the products that it sells as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
32. A boolean flag called "input_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the quantities of the inputs that it is purchasing as a result of current or future sanctions and 0 otherwise.
33. A boolean flag called "input_down", which should be 1 if the firm says it is decreasing or planning to decrease the quantities of the inputs that it is purchasing as a result of current or future sanctions and 0 otherwise.
34. A field called "countries_input_up", listing the countries where the report discusses that the firm is increasing or planning to increase the quantities of the inputs that it is purchasing as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
35. A field called "countries_input_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the quantities of the products as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
36. A boolean flag called "inventory_product_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of inventory of the products it sells as a result of current or future sanctions and 0 otherwise.
37. A boolean flag called "inventory_product_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of inventory of the products it sells as a result of current or future sanctions and 0 otherwise.
38. A boolean flag called "inventory_input_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of inventory of inputs it purchases as a result of current or future sanctions and 0 otherwise.
39. A boolean flag called "inventory_input_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of inventory of inputs it purchases as a result of current or future sanctions and 0 otherwise.
40. A boolean flag called "rd_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of research and development it undertakes as a result of current or future sanctions and 0 otherwise.
41. A boolean flag called "rd_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of research and development it undertakes as a result of current or future sanctions and 0 otherwise.
42. A boolean flag called "delay", which should be 1 if the report discusses that the firm is delaying a decision as a result of current or future sanctions.
43. A boolean flag called "supply_chain_adj", which should be 1 if the report discusses that the firm is adjusting its supply chain as a result of current or future sanctions.
44. A field called "countries_supply_chain_adj_towards", listing the countries where the report discusses that the firm is increasing the exposure of its supply chain as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
45. A field called "countries_supply_chain_adj_away", listing the countries where the report discusses that the firm is reducing the exposure of its supply chain as a result of current or future sanctions. If no country is specified or it is unclear, report "NaN".
46. A boolean flag called "lobbying_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase its lobbying activity as a result of current or future sanctions and 0 otherwise.
47. A boolean flag called "lobbying_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease its lobbying activity as a result of current or future sanctions and 0 otherwise.
48. A boolean flag called "profit_margin_up", which should be 1 if the report discusses that the firm's profit margins have increased or are expected to increase as a result of current or future sanctions and 0 otherwise.
49. A boolean flag called "profit_margin_down", which should be 1 if the report discusses that the firm's profit margins have decreased or are expected to decreased as a result of current or future sanctions and 0 otherwise.
50. A boolean flag called "financing_adj", which should be 1 if the report discusses that the firm is adjusting its financing decisions in response to current or future sanctions.
51. A boolean flag called "negative_impact", which should be 1 if the report discusses any negative impact on the firm's business as a result of current or future sanctions and 0 otherwise.
52. A boolean flag called "positive_impact", which should be 1 if the report discusses any positive impact on the firm's business as a result of current or future sanctions and 0 otherwise.

## Response Instructions: Part 3 (Summary) ##
Write a single summary of 100 words or fewer that captures only how the firm is (or may be) affected by sanctions. Omit all unrelated content. If the firm is not affected by any sanctions, write "Not affected." Enclose this analysis between the tags <SUMMARY> and </SUMMARY>.

## Response Instructions: Part 4 (Evaluation) ##
The fourth part of your response should be an evaluation of how well the JSON structured summary agrees with your initial analysis. Keep the evaluation to 100 words or less. This part of your response should be enclosed between the tags <EVAL> and </EVAL> and be 100 words or less.

## Important Notes ##
- Do not consider import taxes (tariffs) or voluntary boycotts as indications of sanctions. Sanctions must be government-imposed restrictions on trade or financial transactions.
"""

prompt_export_controls = """
You are assisting me in analyzing financial analyst reports. Each report is about a single company. The analyst report will be supplied as the user prompt.

## CRITICAL FOCUS DIRECTIVE ##
You must strictly isolate your analysis to EXPORT CONTROLS ONLY. Given the potential length of the transcript, do not lose focus or hallucinate data. If the firm's actions are driven by other macroeconomic factors or different policies (like tariffs or general sanctions), DO NOT attribute them to export controls. If export controls are not discussed, strictly return 0 and "NaN" for all corresponding fields.

## Response Instructions: Part 1 (Analysis) ##
The first part of your response should be an analysis of whether the analyst is reporting that the firm's decisions are being affected by export control policies. Export controls are defined as restrictions on which countries or foreign firms a company is allowed to sell their goods or services to. In order to be considered export controls, these policies must be imposed by the exporting countries, in contrast to import tariffs, which are instead taxes imposed by the importing country.

This part of your response should be enclosed between the tags <ANALYSIS> and </ANALYSIS>. Keep your analysis to 300 words or less. Make sure to cover all of the following points in your summary analysis:
- Whether export controls are discussed explicitly or implicitly (e.g., by not using the phrase "export controls" but referencing impacts on the firm's business that clearly relate to export controls).
- Whether the report discusses current export controls (i.e., export controls that have already been imposed) or the potential of future export controls (i.e., export controls that have not yet been imposed).
- Whether the report discusses export controls on the goods that the firm sells, or on those that the firm buys.
- The nature and details of the export control policies that are discussed.
- The countries that are imposing the export controls and those that are subject to the export controls.
- Any impacts on the firm's current profits.
- Any potential impact on the firm's future profits.
- Any impacts on the firm's behavior (e.g., in terms of investment, pricing, employment, inventory, R&D, project delay, supply chains, or other future plans).
- Any details on the geographies affected by the changes in the firm's behavior.

## Response Instructions: Part 2 (Structured JSON Output) ##
The second part of your response should be a structured output in JSON format that recaps your analysis in a structured way. This part of your response should be enclosed between the tags <JSON> and </JSON>. The JSON output must have the following fields exactly. Please make sure to enforce the JSON schema specified below strictly: i.e., the column names should correspond exactly to those listed below:
1. A boolean flag called "effect_any", which should be 1 if the report discusses export controls at any point, and 0 otherwise. Even if the term "export controls" is not explicitly used throughout the report, you should return a 1 if the report discusses impacts on the firm's business that clearly relate to export controls.
2. A boolean flag called "effect_current", which should be 1 if the report explicitly or implicitly discusses export controls that are currently in effect and that impact the firm's business, and 0 otherwise. Please do not classify export controls that might imposed in the future as a 1 in this flag.
3. A boolean flag called "effect_future", which should be 1 if the report explicitly or implicitly discusses export controls that might be imposed in the future but are not currently in effect and that might impact the firm's business, and 0 otherwise. Please do not classify export controls that are currently in effect as a 1 in this flag.
4. A field called "countries_imposing", listing the countries whose export control policy the report discusses, if any.
5. A field called "countries_receiving", listing the entities (countries) targeted by the export controls discussed by the report, if any.
6. A field called "product_receiving", listing the goods that the firm sells that are targeted by the export controls, if any.
7. A field called "input_receiving", listing the goods that the firm buys that are targeted by export controls, if any.
8. A boolean flag called "investment_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its investment as a result of current or future export controls and 0 otherwise. Only set the flag to 1 if the report explicitly attributes a change in the firm's investment decisions to export controls.
9. A boolean flag called "investment_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its investment as a result of current or future export controls and 0 otherwise.
10. A field called "countries_investment_up", listing the countries where the report discusses that the firm is increasing or planning to increase investment as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
11. A field called "countries_investment_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease investment as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
12. A boolean flag called "domestic_investment_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its investment in its headquarter country as a result of current or future export controls and 0 otherwise.
13. A boolean flag called "domestic_investment_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its investment in its headquarter country as a result of current or future export controls and 0 otherwise.
14. A boolean flag called "labor_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked as a result of current or future export controls and 0 otherwise.
15. A boolean flag called "labor_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked as a result of current or future export controls and 0 otherwise.
16. A field called "countries_labor_up", listing the countries where the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
17. A field called "countries_labor_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
18. A boolean flag called "domestic_labor_up", which should be 1 if the report discusses that the firm is increasing or planning to increase its number of workers or their hours worked in its headquarter country as a result of current or future export controls and 0 otherwise.
19. A boolean flag called "domestic_labor_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease its number of workers or their hours worked in its headquarter country as a result of current or future export controls and 0 otherwise.
20. A boolean flag called "sales_price_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the price it charges for the products it sells as a result of current or future export controls and 0 otherwise.
21. A boolean flag called "sales_price_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease the price it charges for the products it sells as a result of current or future export controls and 0 otherwise.
22. A field called "countries_sales_price_up", listing the countries where the report discusses that the firm is increasing or planning to increase the price it charges for the products it sells as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
23. A field called "countries_sales_price_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the price it charges for the products it sells as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
24. A boolean flag called "input_price_up", which should be 1 if the firm says it faces or expects to face higher prices on the inputs it purchases as a result of current or future export controls and 0 otherwise.
25. A boolean flag called "input_price_down", which should be 1 if the firm says it faces or expects to face lower prices on the inputs it purchases as a result of current or future export controls and 0 otherwise.
26. A field called "countries_input_price_up", listing the countries where the report discusses that the firm is facing or expecting to face higher prices on the inputs it purchases as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
27. A field called "countries_input_price_down", listing the countries where the report discusses that the firm is facing or expecting to face lower prices on the inputs it purchases as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
28. A boolean flag called "sales_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the quantities of the products that it sells as a result of current or future export controls and 0 otherwise.
29. A boolean flag called "sales_down", which should be 1 if the report discusses that the firm is decreasing or planning to decrease the quantities of the products that it sells as a result of current or future export controls and 0 otherwise.
30. A field called "countries_sales_up", listing the countries where the report discusses that the firm is increasing or planning to increase the quantities of the products that it sells as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
31. A field called "countries_sales_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the quantities of the products that it sells as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
32. A boolean flag called "input_up", which should be 1 if the report discusses that the firm is increasing or planning to increase the quantities of the inputs that it is purchasing as a result of current or future export controls and 0 otherwise.
33. A boolean flag called "input_down", which should be 1 if the firm says it is decreasing or planning to decrease the quantities of the inputs that it is purchasing as a result of current or future export controls and 0 otherwise.
34. A field called "countries_input_up", listing the countries where the report discusses that the firm is increasing or planning to increase the quantities of the inputs that it is purchasing as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
35. A field called "countries_input_down", listing the countries where the report discusses that the firm is decreasing or planning to decrease the quantities of the products as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
36. A boolean flag called "inventory_product_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of inventory of the products it sells as a result of current or future export controls and 0 otherwise.
37. A boolean flag called "inventory_product_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of inventory of the products it sells as a result of current or future export controls and 0 otherwise.
38. A boolean flag called "inventory_input_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of inventory of inputs it purchases as a result of current or future export controls and 0 otherwise.
39. A boolean flag called "inventory_input_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of inventory of inputs it purchases as a result of current or future export controls and 0 otherwise.
40. A boolean flag called "rd_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase the amount of research and development it undertakes as a result of current or future export controls and 0 otherwise.
41. A boolean flag called "rd_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease the amount of research and development it undertakes as a result of current or future export controls and 0 otherwise.
42. A boolean flag called "delay", which should be 1 if the report discusses that the firm is delaying a decision as a result of current or future export controls.
43. A boolean flag called "supply_chain_adj", which should be 1 if the report discusses that the firm is adjusting its supply chain as a result of current or future export controls.
44. A field called "countries_supply_chain_adj_towards", listing the countries where the report discusses that the firm is increasing the exposure of its supply chain as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
45. A field called "countries_supply_chain_adj_away", listing the countries where the report discusses that the firm is reducing the exposure of its supply chain as a result of current or future export controls. If no country is specified or it is unclear, report "NaN".
46. A boolean flag called "lobbying_up", which should be 1 if the report discusses that the firm is increasing or expecting to increase its lobbying activity as a result of current or future export controls and 0 otherwise.
47. A boolean flag called "lobbying_down", which should be 1 if the report discusses that the firm is decreasing or expecting to decrease its lobbying activity as a result of current or future export controls and 0 otherwise.
48. A boolean flag called "profit_margin_up", which should be 1 if the report discusses that the firm's profit margins have increased or are expected to increase as a result of current or future export controls and 0 otherwise.
49. A boolean flag called "profit_margin_down", which should be 1 if the report discusses that the firm's profit margins have decreased or are expected to decreased as a result of current or future export controls and 0 otherwise.
50. A boolean flag called "financing_adj", which should be 1 if the report discusses that the firm is adjusting its financing decisions in response to current or future export controls.
51. A boolean flag called "negative_impact", which should be 1 if the report discusses any negative impact on the firm's business as a result of current or future export controls and 0 otherwise.
52. A boolean flag called "positive_impact", which should be 1 if the report discusses any positive impact on the firm's business as a result of current or future export controls and 0 otherwise.

## Response Instructions: Part 3 (Summary) ##
Write a single summary of 100 words or fewer that captures only how the firm is (or may be) affected by export controls. Omit all unrelated content. If the firm is not affected by any export controls, write "Not affected." Enclose this analysis between the tags <SUMMARY> and </SUMMARY>.

## Response Instructions: Part 4 (Evaluation) ##
The fourth part of your response should be an evaluation of how well the JSON structured summary agrees with your initial analysis. Keep the evaluation to 100 words or less. This part of your response should be enclosed between the tags <EVAL> and </EVAL> and be 100 words or less.

## Important Notes ##
- Do not consider import taxes (tariffs) or generic sanctions as indications of export controls. Export controls must be restrictions imposed by the exporting country.
"""